app:
  name: Weather Notification Service
  description: A service to notify users about extreme weather conditions.
  version: 0.0.1-SNAPSHOT

server:
  port: 8080
  servlet:
    context-path: /api/wsns

weather-api:
  key: ${WEATHER_API_KEY}
  url:
    current: http://api.weatherapi.com/v1/current.json

logging:
  level:
    root: INFO
    com.weathernotification: DEBUG
  file:
    name: logs/weather-sns.log

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
