app:
  name: Weather-SNS
  description: A simple notification service that notifies users about upcoming weather conditions.
  version: 0.0.1-SNAPSHOT

server:
  port: 8080
  servlet:
    context-path: /api/wsns

weather-api:
  key: ${WEATHER_API_KEY}
  url:
    current: http://api.weatherapi.com/v1/current.json

logging:
  level:
    root: INFO
    com.weathernotification: DEBUG
    org:
      springframework:
        security: DEBUG
  file:
    name: logs/weather-sns.log

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: ${app.name}
    description: ${app.description}
    version: ${app.version}
  developer:
    name: Emir Muratčauš
    email: emir.muratcaus97@gmail.com

roles:
  admin:
    usernames: wsns_admin