app:
  name: Weather Notification Service
  description: A service to notify users about extreme weather conditions.
  version: 0.0.1-SNAPSHOT

server:
  port: 8080
  servlet:
    context-path: /api/wsns

weather-api:
  key: ${WEATHER_API_KEY}
  url:
    current: http://api.weatherapi.com/v1/current.json

logging:
  level:
    root: INFO
    com.weathernotification: DEBUG
    org:
      springframework:
        security: DEBUG
  file:
    name: logs/weather-sns.log

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/weather_sns_db
    username: wsns_admin
    password: Cloud2024/
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
