app:
  name: Weather Notification Service
  description: A service to notify users about extreme weather conditions.
  version: 0.0.1-SNAPSHOT

server:
  port: 8080
  servlet:
    context-path: /api

gcp:
  projectId: ${GCP_PROJECT_ID}
  secretName: ${GCP_SECRET_NAME}

weather:
  api:
    url: http://api.weatherapi.com/v1/current.json

logging:
  level:
    root: INFO
    com.weathernotification: DEBUG
  file:
    name: logs/weather-sns.log
